### ISSUE TITLE
[Feature Request]: Renaming the package

### ISSUE THREAD

**Issue by ya0** [insightsengineering/JointModels.jl#30]
### Feature description

Is it possible to renam the repository to `JointModels.jl` with capital letters @danielinteractive? according to the julia [naming convention](https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/):
 >modules and type names use capitalization and camel case: module SparseArrays, struct UnitRange

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by ya0** [comment]
I do not have access to the settings tab.

**Comment by danielinteractive** [comment]
Yeah good point - let me do that for the repo. You can then do it inside the package itself

**Comment by ya0** [comment]
Thanks!
This broke some links to the documentation. I fixed the ones in the readme but I cannot edit the about description on the top right hand side of the project. The `J` and `M` need to be capitalized. @danielinteractive could you do this?
