### ISSUE TITLE
Julia Registrator

### ISSUE THREAD

**Issue by ya0** [insightsengineering/JointModels.jl#40]
### Feature description

To register a package we can install the julia registor on github. 
I requested this access. Maybe you have to install this @danielinteractive 
Here is the link: https://github.com/JuliaComputing/Registrator.jl?tab=readme-ov-file#install-registrator

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
OK let me try this just now

**Comment by danielinteractive** [comment]
So step 1 of the instructions is now done, i.e. the JuliaRegistrator is added to this repo:
![image](https://github.com/insightsengineering/JointModels.jl/assets/1071227/0c484c76-349e-44b7-a499-459d26e78f7e)
So @ya0 you can continue from step 2 in https://github.com/JuliaComputing/Registrator.jl#via-the-github-app
