### ISSUE TITLE
adoptions for release

### ISSUE THREAD

**Issue by ya0** [insightsengineering/JointModels.jl#41]
### Feature description

Concerning: https://github.com/JuliaRegistries/General/pull/100827

- Compat for software
- Possible renaming to something connected to time to event and longitudinal data

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by ya0** [comment]
@danielinteractive the pr #42 again renames the package :) now to `JointSurvivalModels.jl`. Could you please rename the repository and update the description with an updated link to the docs.

**Comment by danielinteractive** [comment]
thanks @ya0, both updated
